<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container91lfpxI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container91lfpxI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container91lfpxI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container91lfpxI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container91lfpxI\App_KernelDevDebugContainer([
    'container.build_hash' => '91lfpxI',
    'container.build_id' => 'ef346188',
    'container.build_time' => 1747141415,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container91lfpxI');
