FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    libonig-dev \
    libxml2-dev \
    zip unzip git curl \
    libpq-dev \
    && docker-php-ext-install pdo_pgsql mbstring pcntl

RUN pecl install xdebug && docker-php-ext-enable xdebug

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY .. /var/www/html

COPY ./docker/php/xdebug.ini /usr/local/etc/php/conf.d/20-xdebug.ini

RUN chown -R www-data:www-data /var/www/html

WORKDIR /var/www/html

EXPOSE 9000
