version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable
    networks:
      - lifehub_network
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: php
    networks:
      - lifehub_network
    build:
      context: .
      dockerfile: docker/php/Dockerfile_dev
    volumes:
      - ./app:/var/www/html

  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:latest
    restart: always
    networks:
      - lifehub_network
    env_file:
      - ./app/.env.db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  lifehub_network:
    external: true
